
all:
	@gcc -Wall exec_test.c -o exec_test
	@gcc -Wall fork_test.c -o fork_test
	@gcc -Wall child.c -o child

	@echo "./exec_test to run exec_test"
	@echo "./fork_test to run fork_test"
	
	
clean:
	rm -rf *.o *.a
